language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"

env:
    - DJANGO="django==1.3.7 --use-mirrors"
    - DJANGO="django==1.4.5 --use-mirrors"
    - DJANGO="django==1.5.1 --use-mirrors"
    - DJANGO="django==1.6.1 --use-mirrors"
    - DJANGO="https://www.djangoproject.com/download/1.7c1/tarball/"

install:
    - pip install $DJANGO
    - pip install coverage==3.6
    - pip install python-coveralls==2.4.0
    - export PYTHONPATH=.

before_script: coverage erase

script: coverage run --source=vanilla manage.py test

after_success: coverage report; coveralls

matrix:
    exclude:
        - python: "2.6"
          env: DJANGO="https://www.djangoproject.com/download/1.7c1/tarball/"
        - python: "3.2"
          env: DJANGO="django==1.4.5 --use-mirrors"
        - python: "3.2"
          env: DJANGO="django==1.3.7 --use-mirrors"
        - python: "3.3"
          env: DJANGO="django==1.4.5 --use-mirrors"
        - python: "3.3"
          env: DJANGO="django==1.3.7 --use-mirrors"
        - python: "3.4"
          env: DJANGO="django==1.6.1 --use-mirrors"
        - python: "3.4"
          env: DJANGO="django==1.5.1 --use-mirrors"
        - python: "3.4"
          env: DJANGO="django==1.4.5 --use-mirrors"
        - python: "3.4"
          env: DJANGO="django==1.3.7 --use-mirrors"

